<?php
require dirname(__DIR__).'/includes/bootstrap.php';
$products=require dirname(__DIR__).'/config/catalog.php';
if(empty($productSlug)||!isset($products[$productSlug])){http_response_code(404);exit('Product not found');}
$product=$products[$productSlug];
$colorCode=(string)($_GET['color']??$product['default_color']);if(!isset($product['colors'][$colorCode]))$colorCode=$product['default_color'];
$dirCode=strtoupper((string)($_GET['dir']??$product['default_direction']));if(!in_array($dirCode,['L','R'],true))$dirCode=$product['default_direction'];
$color=$product['colors'][$colorCode];$sku=$color['sku_base'].'-'.$dirCode;$dirName=$dirCode==='R'?'Вправо':'Влево';$dirNameLower=$dirCode==='R'?'вправо':'влево';$dirArrow=$dirCode==='R'?'Вправо →':'← Влево';
$pageTitle='';$pageDescription='';$pagePath='/catalog/'.$product['slug'].'/';$pageStyles=['/assets/css/catalog.css','/assets/css/catalog-desktop.css','/assets/css/product.css'];$pageScripts=['/assets/js/product.js'];
require dirname(__DIR__).'/includes/head.php';require dirname(__DIR__).'/includes/header.php';require dirname(__DIR__).'/includes/mobile-menu.php';
?>
<main class="product-v2" data-product-root data-base-sku="<?= e($color['sku_base']) ?>" data-product-slug="<?= e($product['slug']) ?>">
<section class="pv2-hero"><div class="pv2-media"><img src="<?= e(asset($product['image'])) ?>" alt="<?= e($product['name'].' '.$product['size']) ?>"><div class="pv2-scheme"><?php require dirname(__DIR__).'/includes/components/product-scheme.php'; ?></div></div>
<div class="pv2-buy"><div class="pv2-meta"><span><?= e($product['model']) ?> · <?= e($product['system']) ?></span><span><?= e($product['mechanism']) ?></span></div><h1><?= e($product['name']) ?><span><?= e($product['title']) ?></span></h1><p class="pv2-sub"><?= e($product['description']) ?></p>
<div class="pv2-price"><strong><?= e($product['price_label']) ?></strong><span><?= e($product['availability']) ?></span></div>
<div class="pv2-option"><div class="pv2-option__head"><span>Цвет</span><strong data-selected-color><?= e($color['name'].' · '.$color['ral']) ?></strong></div><div class="pv2-swatches"><?php foreach($product['colors'] as $code=>$c): ?><a class="pv2-swatch<?= $code===$colorCode?' is-active':'' ?>" href="?color=<?= e($code) ?>&dir=<?= e($dirCode) ?>" data-color-code="<?= e($code) ?>" data-color-name="<?= e($c['name']) ?>" data-ral="<?= e($c['ral']) ?>" data-sku-base="<?= e($c['sku_base']) ?>"><i style="--swatch:<?= $code==='9016'?'#f2f1eb':($code==='7016'?'#353a3c':($code==='7024'?'#4c5051':'#111')) ?>"></i><span><?= e($c['name']) ?><small><?= e($c['ral']) ?></small></span></a><?php endforeach; ?></div></div>
<div class="pv2-option"><div class="pv2-option__head"><span>Направление открывания</span><strong data-selected-direction><?= e($dirArrow) ?></strong></div><div class="pv2-directions"><a class="pv2-direction<?= $dirCode==='L'?' is-active':'' ?>" href="?color=<?= e($colorCode) ?>&dir=L" data-dir="L"><span>←</span> Влево</a><a class="pv2-direction<?= $dirCode==='R'?' is-active':'' ?>" href="?color=<?= e($colorCode) ?>&dir=R" data-dir="R">Вправо <span>→</span></a></div></div>
<div class="pv2-micro"><div><span>Статус</span><strong><?= e($product['availability']) ?></strong></div><div><span>Срок</span><strong><?= e($product['lead_time']) ?></strong></div></div>
<div class="pv2-actions"><button class="btn btn--fill" type="button" data-add-cart>В корзину <span>→</span></button><a class="btn" href="/calculator/?product=<?= e($product['slug']) ?>">Другой размер <span>↗</span></a></div>
<p class="pv2-sku">SKU <strong data-sku><?= e($sku) ?></strong></p></div></section>
<section class="pv2-section"><div class="wrap"><div class="pv2-kicker">01 / Конфигурация</div><div class="pv2-grid"><div><h2>Архитектурная система, оформленная как конкретный товар.</h2><p>Цена, размер, профиль, фурнитура, цвет и направление открытия фиксируются на уровне SKU. Это позволяет сохранить чистый интерфейс и не превращать каталог в десятки визуально одинаковых карточек.</p></div><div class="pv2-config"><div class="pv2-config__scheme"><?php require dirname(__DIR__).'/includes/components/product-scheme.php'; ?></div><div class="pv2-config__facts"><span><?= e($product['size']) ?></span><span><?= e($product['panes'].' секции · активных '.$product['active']) ?></span><span data-direction-fact>Открывание: <?= e($dirNameLower) ?></span></div></div></div></div></section>
<section class="pv2-photo"><img src="<?= e(asset($product['image_alt'] ?: $product['image'])) ?>" alt=""><div><span><?= e($product['model'].' / '.$product['system']) ?></span><span>Product study</span></div></section>
<section class="pv2-section pv2-spec"><div class="wrap"><div class="pv2-kicker">02 / Спецификация</div><div class="pv2-specgrid"><div><div class="pv2-row"><span>Система</span><strong><?= e($product['system']) ?></strong></div><div class="pv2-row"><span>Фурнитура</span><strong><?= e($product['hardware']) ?></strong></div><div class="pv2-row"><span>Размер</span><strong><?= e($product['size']) ?></strong></div><div class="pv2-row"><span>Цвет</span><strong data-spec-color><?= e($color['name'].' · '.$color['ral']) ?></strong></div><div class="pv2-row"><span>Покрытие</span><strong><?= e($color['finish']) ?></strong></div><div class="pv2-row"><span>Статус</span><strong><?= e($product['availability']) ?></strong></div><div class="pv2-row"><span>Срок</span><strong><?= e($product['lead_time']) ?></strong></div></div><div class="pv2-info"><details open><summary>Стеклопакет</summary><p><?= $product['family']==='hs'?'44 мм · двухкамерный':'40 мм · двухкамерный' ?>. Подробная формула хранится в технических данных и будет зафиксирована перед публикацией.</p></details><details><summary>Товарные поля</summary><p>Подготовлены: SKU, цена, availability, lead time, цвет/RAL, направление, профиль, фурнитура, размер. SEO URL, YML name, picture URL, delivery и JSON-LD пока намеренно пустые.</p></details></div></div></div></section>
<section class="pv2-tech"><div class="wrap"><div class="pv2-kicker">03 / Data</div><h2>Один источник данных для карточки, корзины и будущего merchant feed.</h2><div class="pv2-data"><div><span>Base model</span><strong><?= e($product['model']) ?></strong></div><div><span>Offer SKU</span><strong data-sku-copy><?= e($sku) ?></strong></div><div><span>Color</span><strong data-data-color><?= e($color['ral']) ?></strong></div><div><span>Direction</span><strong data-data-direction><?= e($dirName) ?></strong></div></div></div></section>
</main>
<div class="pv2-mobile-buy"><div><span><?= e($product['availability']) ?></span><strong><?= e($product['price_label']) ?></strong></div><button class="btn btn--fill" type="button" data-add-cart>В корзину →</button></div>
<?php require dirname(__DIR__).'/includes/footer.php';require dirname(__DIR__).'/includes/scripts.php'; ?>
